# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0014_auto_20170516_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether the form entry is locked against editing.', verbose_name='Locked against editing?'),
        ),
    ]
