# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0015_formentry_is_locked'),
        ('fobi', '0015_auto_20180130_0013'),
    ]

    operations = [
    ]
